# Railway configuration - 500g Bag Support Deployment
# This configuration includes 500g bag support for retail ordering
# FORCE REBUILD: $(date) - 500g bag support deployed
# IMPORTANT: Use Dockerfile builder since Nixpacks is failing
# LAST UPDATE: 2025-01-28 20:00 - 500g bag support deployment
# UNIQUE ID: medium-bags-fixed-$(date +%s) - Force Railway rebuild with DB fix
# FORCE RESTART: Adding 500g bag support configuration

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health-basic"
healthcheckTimeout = 300
restartPolicyType = "ALWAYS"

[database]
name = "postgres"

# Add new section to force configuration change
[monitoring]
enabled = true 