# Railway configuration - FORCE COMPLETE RESTART
# This configuration was working before we broke it
# FORCE REBUILD: $(date) - Push notification fixes deployed
# IMPORTANT: Use Dockerfile builder since Nixpacks is failing
# LAST UPDATE: 2025-01-28 15:30 - FORCE RAILWAY TO USE NEW DEPLOYMENT
# UNIQUE ID: $(date +%s) - Force Railway rebuild
# FORCE RESTART: Adding completely new configuration

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health-basic"
healthcheckTimeout = 300
restartPolicyType = "ALWAYS"

[database]
name = "postgres"

# Add new section to force configuration change
[monitoring]
enabled = true 