[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run railway:start"
healthcheckPath = "/api/health-basic"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
NODE_ENV = "production"
PORT = "3000"
COOKIE_SECURE = "true"
COOKIE_SAMESITE = "none"

# Note: Make sure to set these secrets in the Railway dashboard
# DATABASE_URL
# JWT_SECRET

[services.web]
autoDeploy = true 