[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/api/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
NODE_ENV = "production"
PORT = "8080"

# Note: Make sure to set these secrets in the Railway dashboard
# DATABASE_URL
# JWT_SECRET

[services.web]
autoDeploy = true 