[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "./docker-entrypoint.sh"
healthcheckPath = "/api/admin/test-db"
healthcheckTimeout = 60

[environments]
NODE_ENV = "production" 