# Railway configuration - FORCE REBUILD
# This file forces Railway to use Next.js instead of custom server

[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[database]
name = "postgres" 