# Railway configuration - FORCE NIXPACKS REBUILD
# This configuration was working before we broke it
# FORCE REBUILD: $(date) - Push notification fixes deployed
# IMPORTANT: Use NIXPACKS builder, not Dockerfile

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[database]
name = "postgres" 