# Railway configuration - RESTORED WORKING VERSION
# This configuration was working before we broke it
# FORCE REBUILD: $(date) - Push notification fixes deployed

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[database]
name = "postgres" 